//
//  AppDatabase.swift
//  TempProject
//
//  Created Eugene Software on 11/12/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation
import UIKit
import CoreData

/// A type responsible for initializing the application's database
public struct AppDatabase {

    public static func openDatabase(in application: UIApplication) {
        
        //Initialize core data stack
        //
        _ = CoreDataStorageController.shared
    }
    
    public static func deleteDatabase(keeping tablesToKeep: [NSManagedObject.Type], completion: (() -> Void)?) {
        
        let tablesToKeepNames = tablesToKeep.map { String(describing: $0) }
        CoreDataStorageController.shared.deleteAllTables(except: tablesToKeepNames, completion: completion)
    }
}
